---
- hosts: all
  # vars_files:
  #   - secrets.yml
  become: yes
  gather_facts: true
  roles:
    - { role: ansible-role-consul, tags: [ 'consul' ] }
    - { role: ansible-role-nomad, tags: [ 'nomad' ] }