#!/bin/bash

# Part 1: Static MySQL Secret Rotation Demo
# This script orchestrates the complete static MySQL secret rotation demonstration

set -e

echo "=== Part 1: Static MySQL Secret Rotation Demo ==="
echo

# Check prerequisites
if ! command -v vault &> /dev/null; then
    echo "❌ Vault CLI not found. Please install Vault."
    exit 1
fi

if ! vault status >/dev/null 2>&1; then
    echo "❌ Vault is not running or not accessible."
    echo "   Please start Vault dev server: vault server -dev"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo "❌ jq not found. Please install jq for JSON processing."
    exit 1
fi

if ! docker ps -q -f name=vault-mysql-demo >/dev/null 2>&1; then
    echo "❌ MySQL container not running. Starting it now..."
    ./mysql-setup.sh
fi

echo "✅ Prerequisites satisfied"
echo

# Show the static rotation flow
echo "📋 Static Secret Rotation Flow (MySQL Database):"
echo "   1. 🔑 Vault generates new password (using password policies)"
echo "   2. 📥 User retrieves password from Vault"
echo "   3. 🗄️  User updates MySQL database with new password"
echo "   4. 📝 User updates application configuration"
echo "   5. 🏦 User stores credential metadata in Vault"
echo "   6. 🚀 Applications retrieve updated credential from Vault"
echo

# Show current state
echo "🔍 Current State Before Rotation:"
echo "================================="
echo
echo "📊 Current MySQL service account:"
echo "   Username: app-service-user"
echo "   Password: initial-static-password (static, never rotated)"
echo
echo "🔗 Testing current connection:"
if docker exec vault-mysql-demo mysql -u app-service-user -pinitial-static-password demo -e "
SELECT 
    'Current connection works' as Status,
    USER() as Connected_As,
    COUNT(*) as Total_Records
FROM users;" 2>/dev/null; then
    echo "   ✅ Current static password works"
else
    echo "   ❌ Current connection failed"
fi
echo

# Show Vault password policy
echo "🔒 Password Policy for MySQL Rotation:"
echo "======================================"
echo "   Policy Name: mysql-static-policy"
echo "   Length: 24 characters"
echo "   Character Sets: letters, numbers, @#% (database-safe)"
echo
echo "🎲 Sample password generation:"
SAMPLE_PASSWORD=$(vault read -field=password sys/policies/password/mysql-static-policy/generate)
echo "   Generated: ${SAMPLE_PASSWORD:0:6}****${SAMPLE_PASSWORD: -6}"
echo "   Length: ${#SAMPLE_PASSWORD} characters"
echo

# Show current Vault state
echo "📚 Current Vault State:"
echo "======================"
echo "🔍 Stored credential:"
vault kv get static-secrets/mysql/service-accounts/app-service-user | grep -E "(username|password|rotation_status|created)"
echo

# Wait for user to continue
read -p "Press Enter to perform password rotation..."
echo

# Perform the rotation
echo "🔄 Performing Static MySQL Password Rotation:"
echo "=============================================="
./rotate-mysql-password.sh
echo

# Show the difference - what changed
echo "🔍 What Changed After Rotation:"
echo "==============================="
echo
echo "📊 MySQL Database:"
echo "   • Service account password updated"
echo "   • Old password no longer valid"
echo "   • New password generated by Vault policy"
echo
echo "📝 Application Configuration:"
echo "   • Config file updated with new password"
echo "   • Rotation timestamp recorded"
echo "   • Backup created for rollback"
echo
echo "🏦 Vault Storage:"
echo "   • New credential version stored"
echo "   • Metadata includes rotation details"
echo "   • Version history maintained"
echo

# Test the final state
echo "🧪 Final Verification:"
echo "====================="
echo
echo "🔗 Testing with credentials from Vault:"
VAULT_CREDS=$(vault kv get -format=json static-secrets/mysql/service-accounts/app-service-user)
VAULT_USERNAME=$(echo $VAULT_CREDS | jq -r '.data.data.username')
VAULT_PASSWORD=$(echo $VAULT_CREDS | jq -r '.data.data.password')

if docker exec vault-mysql-demo mysql -u $VAULT_USERNAME -p$VAULT_PASSWORD demo -e "
SELECT 
    'Rotation successful!' as Status,
    USER() as Connected_As,
    NOW() as Connection_Time,
    (SELECT COUNT(*) FROM users) as Total_Users,
    (SELECT COUNT(*) FROM orders) as Total_Orders;" 2>/dev/null; then
    echo "   ✅ Application can successfully connect using rotated credentials from Vault"
else
    echo "   ❌ Connection failed with rotated credentials"
fi
echo

# Show version history
echo "📚 Credential Version History:"
echo "============================="
vault kv metadata get static-secrets/mysql/service-accounts/app-service-user | grep -A 15 "Versions:"
echo

# Compare with what's coming in Part 2
echo "🔄 Static vs Dynamic Comparison:"
echo "================================"
echo
echo "❌ What we just saw (Static Rotation):"
echo "   • Manual password rotation required"
echo "   • Long-lived credentials exist in MySQL"
echo "   • Target system must be updated manually"
echo "   • Applications use same credential for extended periods"
echo "   • Still significant security improvement over never rotating"
echo
echo "✅ What's coming in Part 2 (Dynamic Secrets):"
echo "   • Automatic credential generation on-demand"
echo "   • Short-lived credentials (minutes/hours)"
echo "   • No manual updates to target system"
echo "   • Each application request gets unique credentials"
echo "   • Ultimate security: credentials expire automatically"
echo

echo "✅ Part 1 Demo Complete!"
echo
echo "🎯 Key Takeaways for Static Rotation:"
echo "   • Vault can generate passwords instead of humans"
echo "   • Password policies ensure consistent complexity"
echo "   • Manual coordination required between systems"
echo "   • Significant security improvement over static passwords"
echo "   • Version history enables rollback capabilities"
echo "   • Good for legacy systems that can't use dynamic secrets"
echo
echo "💡 Next: Part 2 will show dynamic secrets with the same MySQL database"